Add Polars backend
tconbeer/textual-fastdatatable pull request #112
Opened 2024-06-21 01:05 UTC by kdkavanagh

Closes #96

2024-06-22 00:12 UTC, tconbeer commented
Thanks for this! I'm away from my computer for a little while but I'll give you a review when I get back

2024-06-24 21:20 UTC, tconbeer requested changes
This looks really good -- I'd just prefer if the dependency on Polars was optional. Also curious how this backend benchmarks vs. arrow?

2024-06-24 21:20 UTC, tconbeer commented on src/textual_fastdatatable/backend.py
> +        )
```suggestion
        if pl is not None:
            return PolarsBackend.from_file_path(
                data, max_rows=max_rows, has_header=has_header
            )
```

2024-06-24 21:20 UTC, tconbeer commented on src/textual_fastdatatable/backend.py
> +    def __init__(self, data: pl.DataFrame, max_rows: int | None = None) -> None:
Would be good to throw a friendly exception here if Polars isn't installed (`pl is None`)

2024-06-26 03:35 UTC, kdkavanagh commented
Updated - I moved the whole class definition under the `try`.  This makes pylint/mypy a bit happier + avoids needing all the `if not none` checks

2024-06-26 23:51 UTC, kdkavanagh commented
Benchmark results suggest it may be the fastest impl:

Records |Built-In DataTable | FastDataTable (Arrow from Parquet) | FastDataTable (Arrow from Records) | FastDataTable (Polars from Parquet)
--------|--------|--------|--------|--------
lap_times_100.parquet |   0.008s /   1.304s |   0.006s /   1.406s |   0.007s /   1.441s |   0.023s /   1.145s
lap_times_1000.parquet |   0.050s /   1.749s |   0.007s /   1.933s |   0.005s /   1.866s |   0.005s /   1.098s
lap_times_10000.parquet |   0.339s /   1.985s |   0.006s /   1.909s |   0.009s /   1.862s |   0.005s /   1.107s
lap_times_100000.parquet |   3.171s /   4.755s |   0.012s /   1.895s |   0.053s /   1.932s |   0.013s /   1.096s
lap_times_538121.parquet |  17.126s /  18.921s |   0.025s /   1.933s |   0.272s /   2.138s |   0.033s /   1.131s
wide_10000.parquet |   2.216s /   5.913s |   0.009s /   2.362s |   0.023s /   2.291s |   0.007s /   1.086s
wide_100000.parquet |  22.291s /  26.005s |   0.023s /   2.300s |   0.184s /   2.552s |   0.011s /   1.091s

2024-07-09 17:02 UTC, tconbeer requested changes

2024-07-09 17:02 UTC, tconbeer commented on pyproject.toml
> +polars = { version = ">=0.20.0", optional = true }
You'll also need to add `polars` as a test dependency in the `tool.poetry.group.test.dependencies` below.

2024-07-09 17:02 UTC, tconbeer commented on pyproject.toml
> +polars = { version = ">=0.20.0", optional = true }
(and also as an `additional_dependency` for the `mypy` hook in `pre-commit-config.yaml`)

2024-07-09 17:02 UTC, tconbeer commented on src/textual_fastdatatable/__init__.py
> +    PolarsBackend,
This only exists if `_HAS_POLARS`

2024-07-09 17:03 UTC, tconbeer commented
The benchmark results are exciting -- the optional import stuff still needs some work, though.

2024-07-11 22:11 UTC, merged